# Generated by Django 3.2 on 2021-05-10 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('major', '0002_car_education_warcraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to=settings.AUTH_USER_MODEL),
        ),
    ]
